use pureessence;
-- Categories
-- _____________

insert into CATEGORIA(nome, descrizione)
values (
     "make-up",
     "Il trucco è sempre stato e sempre sarà al centro della routine di bellezza della persona. Scopri ora il catalogo PureEssence e lasciati ispirare dalla nostra idea di make-up."
);

insert into CATEGORIA(nome, descrizione)
values (
     "viso",
     "La formula della bellezza passa per la cura del viso. Scopri la linea PureEssence e trova i trattamenti e i prodotti migliori per curare e valorizzare il tuo viso."
);

insert into CATEGORIA(nome, descrizione)
values (
     "capelli",
     "Che siano ricci, lisci, crespi o mossi, tutti cercano di trovare il miglior modo per valorizzare e curare i propri capelli. Scopri il catalogo PureEssence e trova il prodotto più giusto per te."
);

insert into CATEGORIA(nome, descrizione)
values (
     "corpo",
     "Nella routine di bellezza quotidiana, nulla è importante come la cura della pelle. Scopri la collezione di prodotti corpo PureEssence e trova tutto ciò di cui hai bisogno per una pelle perfetta."
);

insert into CATEGORIA(nome, descrizione)
values (
     "profumi",
     "Che sia per un'occasione speciale, o per la tua vita quotidiana, PureEssence ha il profumo giusto per te. Scopri il nostro catalogo e trova la migliore fragranza per le tue esigenze."
);

-- Seller profile
-- _____________

insert into VENDITORE(username, password, email, telefono)
values ("pureessence", "c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec", "admin@pureessence.it", "");

INSERT INTO `marca` (`nome`) VALUES
('111SKIN'),
('ARMANI'),
('AUDRER'),
('BEAUTY OF JOESON'),
('CHANEL'),
('CHARLOTTE TILBURY'),
('CLINIQUE'),
('COLOR WOW'),
('DIOR'),
('ERBORIAN'),
('FENTY SKIN'),
('GISOU'),
('GIVENCHY'),
('K18'),
('KERASTASE'),
('LANCOM'),
('LANEIGE'),
('MOROCCANOIL'),
('NABLA'),
('NARCISO RODRIGUEZ'),
('NARS'),
('OLAPLEX'),
('RARE BEAUTY'),
('REDKEN'),
('RITUALS'),
('SHISEIDO'),
('SOL DE JANEIRO'),
('THE ORDINARY'),
('TOM FORD'),
('VERSACE'),
('YEPODA'),
('YVES SAINT LAURENT');

INSERT INTO `sottocategoria` (`nome`, `categoria`) VALUES
('Maschere', 'capelli'),
('Oli', 'capelli'),
('Shampoo a secco', 'capelli'),
('Temoprotettori', 'capelli'),
('Trattamenti Capelli', 'capelli'),
('Crema idratante', 'corpo'),
('Crema mani', 'corpo'),
('Olio', 'corpo'),
('Profumi corpo', 'corpo'),
('Solari', 'corpo'),
('Trattamenti corpo', 'corpo'),
('Detergenti', 'make-up'),
('Labbra', 'make-up'),
('Occhi', 'make-up'),
('Palette', 'make-up'),
('Donna', 'profumi'),
('Uomo', 'profumi'),
('Antietà', 'viso'),
('Creme solari', 'viso'),
('Esfolianti', 'viso'),
('Idratanti', 'viso'),
('Peeling', 'viso'),
('Sieri ', 'viso'),
('Tonico', 'viso');


INSERT INTO `prodotto` (`IDprodotto`, `nome`, `didascalia`, `descrizione`, `URLimmagine`, `marca`, `sottocategoria`, `istruzioni`, `ingredienti`, `avvertenze`) VALUES
(1, 'No.3 Hair Perfector™', 'Trattamento Settimanale Per Capelli', 'Un potente trattamento pre-shampoo dall’efficacia clinicamente testata, che rende i capelli 3 volte più forti dopo un solo utilizzo', 'capelli/trattamenti/olaplex/001.jpg', 'OLAPLEX', 'Trattamenti Capelli', 'Sotto la doccia, prima dello shampoo, applica il N°.3 dalle radici fino alle punte fino a impregnare completamente i capelli. Lascia in posa per 3-10 minuti e risciacqua bene. Prosegui con lo shampoo N°.4 Bond Maintenance® e il balsamo N°.5 Bond Maintenance®.', 'Water (Aqua/Eau) ,Cetearyl Alcohol,PPG-3 Benzyl Ether Myristate, Caprylic/Capric Triglyceride , Cetyl Alcohol,Octyldodecyl Ricinoleate, Quaternium-91 , Cetrimonium Chloride, Divinyldimethicone/Dimethicone Copolymer , Behentrimonium Chloride , Glycerin', 'Evita il contatto con gli occhi.'),
(2, 'ONE UNITED', 'Spray Leave-In per tutti i tipi di capelli ', 'Trattamento spray per capelli con 25 benefici che aumentano la maneggiabilità, la protezione e la bellezza. Offre benefici legati al trattamento per aumentarne la maneggiabilità, la protezione e la bellezza. Ammorbidisce la texture dei prodotti per la piega. Idrata e nutre il capello, contribuisce a levigare i capelli porosi, riduce la disidratazione dei capelli, li rende più lisci e scioglie i nodi.', 'capelli/trattamenti/redken/003.jpg', 'REDKEN', 'Trattamenti Capelli', 'Dopo lo shampoo, spruzzare uniformemente sui capelli umidi o tamponati con un asciugamano. Non risciacquare per ottenere un effetto condizionante profondo. Risciacquare dopo 1-2 minuti per un effetto condizionante leggero.', 'Aqua / Water / Eau, Cocos Nucifera Oil / Coconut Oil, Amodimethicone, Polyquaternium-37, Phenoxyethanol, Propylene Glycol Dicaprylate / Dicaprate, Parfum / Fragrance, Acetamide MEA, Lactamide MEA, Dimethicone PEG-7 Phosphate, PPG-1 Trideceth-6, Trideceth-6, Behentrimonium Chloride, Xylose', 'In caso di contatto con gli occhi, sciacquarli immediatamente e abbondantemente.'),
(3, 'Genesis Serum', 'Siero anti caduta temporanea', 'Siero fortificante anti-caduta occasionale per capelli indeboliti e propensi alla caduta da usare quotidianamente. Aumenta la resistenza del capello minimizzando la caduta occasionale, e rende i capelli più splendenti.', 'capelli/trattamenti/kerastase/002.jpg', 'KERASTASE', 'Trattamenti Capelli', 'Utilizzare una volta al giorno la mattina o prima di andare a letto per un periodo di 6 settimane. Applicare 4 pressioni su capelli asciutti o tamponati, sezione per sezione. 1 applicazione = 1 pipetta fino al segno.', '227619 B - INGREDIENTS: AQUA / WATER / EAU • ALCOHOL DENAT. • DIAMINOPYRIMIDINE OXIDE • AMMONIUM POLYACRYLOYLDIMETHYL TAURATE • AMINOMETHYL PROPANOL • CITRIC ACID • PEG-40 HYDROGENATED CASTOR OIL • PIROCTONE OLAMINE', 'Non sono necessarie precauzioni specifiche per l’uso di questo prodotto in condizioni normali o ragionevolmente prevedibili di utilizzo.'),
(4, 'K18', 'Repair Hair Mask ', 'Una maschera di trattamento leave-in per tutti i tipi di capelli, che ripara i danni in soli quattro minuti. K18PEPTIDE™ ripara i capelli danneggiati da decolorazioni, tinte per capelli, trattamenti chimici e calore, restituendo forza, morbidezza ed elasticità alla chioma.', 'capelli/trattamenti/k18/004.jpg', 'K18', 'Maschere', '- Tamponare delicatamente i capelli.\r\n- Per iniziare, versare un ml/una piccola quantità di maschera K18 tra le mani.\r\n- Massaggiare uniformemente sui capelli, dalle punte alle radici.\r\n- Lasciare in posa per quattro minuti.\r\n- Non risciacquare', 'Water (Aqua) (Eau), Alcohol Denat., Propylene Glycol, Cetearyl Alcohol, Dicaprylyl Ether, Cetyl Esters, Behentrimonium Chloride, Polysorbate 20, sh-Oligopeptide-78 (K18PEPTIDE), Hydrolyzed Wheat Protein, Hydrolyzed Wheat Starch', 'Nessuna avvertenza.'),
(5, 'No.7 Bonding Oil', 'Olio Per Capelli', 'Un olio per lo styling altamente concentrato e leggero per tutti i tipi di capelli. Bastano 2 o 3 gocce per ottenere all’istante più lucentezza e morbidezza, rafforzare i capelli per ridurre le rotture e controllare l’effetto crespo e le ciocche ribelli per capelli visibilmente sani e in ordine.', 'capelli/trattamenti/olaplex/101.png', 'OLAPLEX', 'Oli', '1. Apri il flacone e capovolgilo. 2. Picchietta delicatamente il fondo per rilasciare una goccia dosata. 3. Distribuisci 2 o 3 gocce sui capelli umidi o asciutti, acconciandoli come fai di solito.', 'Dimethicone, Isohexadecane, C13-14 Isoparaffin, Coco-Caprylate, Phenyl Trimethicone, Bis-Aminopropyl Diglycol Dimaleate, Propanediol, Zea Mays (Corn) Oil, Beta-Carotene, Helianthus Annuus (Sunflower) Seed Oil, Punica Granatum Seed Oil, Water (Aqua)', 'Evitare il contatto con gli occhi.\r\n\r\n'),
(6, 'N°5', 'Eau De Parfum', 'N°5, l’essenza stessa della femminilità.\r\nUn bouquet fiorito-aldeidato, sublimato in un flacone iconico dalle linee minimaliste. Un profumo mitico e intramontabile. L’Eau de Parfum s’ispira all’Estratto, con il quale condivide la firma fiorito-aldeidata. Questo bouquet fiorito, declinato intorno alla rosa di maggio e al gelsomino, è allegro e vivace grazie alle note di testa esperidate.', 'profumi/Donna/chanel/4243.jpg', 'CHANEL', 'Donna', 'L’Eau de Parfum in versione vaporizzatore, per una gestualità ampia e semplice, sulla pelle o sui vestiti.', 'ALCOHOL | AQUA (WATER) | PARFUM (FRAGRANCE) | BENZYL ALCOHOL | BENZYL BENZOATE | BENZYL CINNAMATE | BENZYL SALICYLATE | CINNAMYL ALCOHOL | CITRAL | CITRONELLOL | COUMARIN | EUGENOL | FARNESOL | GERANIOL | HYDROXYCITRONELLAL | ISOEUGENOL | LIMONENE | LINALOOL | ALPHA-ISOMETHYL IONONE', 'Nessuna avvertenza.'),
(8, 'Hypnotic Poison', 'Eau de Toilette', 'L’eau de toilette Hypnotic Poison è una fragranza magnetica, un profumo orientale e inebriante. “Hypnotic Poison è una fragranza orientale infusa di uno spirito insolente e conquistatore, nata per sconvolgere e catturare l’attenzione.” François Demachy, Parfumeur-Créateur Dior. Le note di vaniglia sprigionano accordi dolci e speziati e, al contempo, si mischiano alle note di mandorla e gelsomino per comporre questo profumo eccezionalmente sensuale e come magnetico.', 'profumi/Donna/dior/hypnotic-poison/2726.jpg', 'DIOR', 'Donna', '1. Prepara la pelle con il latte satinato per il corpo Hypnotic Poison.\r\n2. Applica l’eau de toilette Hypnotic Poison sui punti di pulsazione: in corrispondenza dei polsi, sul collo e dietro le orecchie.\r\n3. Come tocco finale, vaporizza il deodorante Hypnotic Poison.', '60353\r\n#08031/A ALCOHOL, AQUA (WATER), PARFUM (FRAGRANCE), BHT, LINALOOL, LIMONENE, BENZYL ALCOHOL &ndash', 'Nessuna avvertenza.'),
(9, 'L’Interdit', 'Eau de Parfum', 'Con una miscela proibita di fiori bianchi e un accordo scuro, L’Interdit Eau de Parfum è un fiore decisamente underground. La fragranza rivela un sensuale bouquet di Fiori d’Arancio, Gelsomino e Tuberosa. Le note scure e terrose del Vetiver e del Patchouli, invece, creano un contrasto che dà vita a una fragranza irresistibile e sensuale. In omaggio al design del primo profumo di Hubert de Givenchy, il flacone è senza tempo ma decisamente moderno. La forma quadrata dai lati smussati e la forza delicata che lo caratterizzano invitano a infrangere le regole e lasciarsi andare.', 'profumi/Donna/givenchy/interdit/322.png', 'GIVENCHY', 'Donna', 'Spruzzare L’Interdit Eau de Parfum direttamente sulla pelle, soprattutto sulle parti calde del corpo: all’interno dei polsi, dietro le orecchie e sul collo.', 'ALCOHOL, PARFUM (FRAGRANCE), AQUA (WATER), ETHYLHEXYL METHOXYCINNAMATE, LINALOOL, LIMONENE, BUTYL METHOXYDIBENZOYLMETHANE, BUTYLENE GLYCOL DICAPRYLATE/DICAPRATE, CITRONELLOL, GERANIOL, BHT, BENZYL SALICYLATE, EUGENOL, ALPHA-ISOMETHYL IONONE, TOCOPHEROL, CITRAL, COUMARIN, BENZYL ALCOHOL, CI 19140 ', 'Nessun avvertenza.'),
(10, 'Black Opium', 'Eau De Parfum', 'BLACK OPIUM, il profumo femminile YSL Beauty sfrontato e irresistibile, in cui l’energia elettrizzante del caffè nero incontra l’assertività dei fiori bianchi e della vaniglia. La tua dose di energia in un profumo che dona il coraggio di essere unica. Black come il colore simbolo del rock, il colore di una moderna e metropolitana eleganza, l’espressione di una dipendenza. Un contrasto vibrante, sensuale e addictive di luce e oscurità. Il suo messaggio è "Infrangi le regole, assumi la tua dose di BLACK OPIUM per rendere la tua vita rock". Irresistibile più che mai, il flacone storico di Opium viene rivisitato nella chiave più moderna. I glitter neri donano una scintillante connotazione edgy che elettrizza e rende unica l’intensità della laccatura nera, fino a rivelare una sfacciata femminilità nell’anello sfolgorante al centro.', 'profumi/Donna/ysl/black opium/00.jpg', 'YVES SAINT LAURENT', 'Donna', 'La fragranza è intensificata dal calore del tuo corpo. \r\n\r\nPer una maggiore intensità e persistenza, applicare il profumo nei punti caldi: polsi, collo e petto.', 'ALCOHOL , PARFUM / FRAGRANCE , AQUA / WATER , BENZYL SALICYLATE , BENZYL ALCOHOL , HYDROXYCITRONELLAL , BUTYL METHOXYDIBENZOYLMETHANE , HEXYL CINNAMAL, LIMONENE , LINALOOL , GERANIOL , CITRONELLOL , CINNAMYL ALCOHOL , METHYL ANTHRANILATE', 'Precauzioni d’uso: infiammabile finche’ non e’ secco. Tenere lontano da fiamme e calore. Evitare di vaporizzare verso gli occhi'),
(11, 'Libre', 'Eau de Parfum', 'LIBRE, il profumo femminile YSL Beauty che esprime la libertà di vivere la vita secondo le proprie regole. Una fragranza floreale audace, in cui l’essenza della lavanda francese si unisce ai sensuali fiori di arancio del Marocco e agli ardenti accordi di muschio per creare un profumo unico e persistente.\r\n\r\nIl flacone ricaricabile ispirato alla couture è impreziosito da una solenne cassandra oro incastonata nel vetro come un gioiello, sensuali catene dorate e un tappo laccato nero.', 'profumi/Donna/ysl/libre/333.png', 'YVES SAINT LAURENT', 'Donna', 'La fragranza è intensificata dal calore del tuo corpo. \r\nPer una maggiore intensità e persistenza, applicare il profumo nei punti caldi: polsi, collo e petto.\r\n\r\nRicarica a casa in 3 semplici step:\r\n1. Una volta che il flacone è vuoto, svita lo spray.\r\n2. Posiziona la ricarica sulla bottiglia, quind', '875178 50 - INGREDIENTS: ALCOHOL • PARFUM / FRAGRANCE • AQUA / WATER / EAU • LIMONENE • LINALOOL • BENZYL SALICYLATE • HYDROXYCITRONELLAL • BENZYL ALCOHOL • ETHYLHEXYL SALICYLATE • BUTYL METHOXYDIBENZOYLMETHANE • COUMARIN • GERANIOL • METHYL ANTHRANILATE • CITRONELLOL • CITRAL • ISOEUGENOL', 'Precauzioni d’uso: infiammabile finche’ non e’ secco. Tenere lontano da fiamme e calore. Evitare di vaporizzare verso gli occhi'),
(12, 'For her', 'Eau de Toilette', 'For her è un profumo immaginato come un omaggio alle donne. Questa fragranza semplice ed essenziale, pensata per la donna sensuale ed elegante, offre un viaggio nel cuore del muschio, alla scoperta delle sue numerose e delicate sfaccettature. \r\n\r\nfor her eau de toilette è una fragranza basata su tre accordi olfattivi. L’accordo “miele di fiori” svela un muschio solare dagli accenti freschi di fiori d’arancio e di osmanto. L’accordo “luce d’ambra” trasporta il muschio verso un’espressione più astratta, in cui la sua delicatezza impalpabile diventa avvolgente. È un muschio luminoso, che conserva però una ricchezza cremosa conferita dall’amberlyn e dalla vaniglia. Infine, l’accordo “legno” sviluppa pienamente la dimensione sensoriale del muschio.  Il vetiver acquisisce un tocco femminile e la sensualità delle note legnose diventa sublime.', 'profumi/Donna/narciso/toilette/fdsda.png', 'NARCISO RODRIGUEZ', 'Donna', 'Per un’applicazione coinvolgente e una scia più intensa:\r\n\r\n- Utilizzare il gel doccia for her \r\n\r\n- Applicare la crema corpo for her\r\n\r\n- Applicare il deodorante for her\r\n\r\n- Vaporizzare for her eau de toilette sui punti di pulsazione\r\n\r\n- Sublimare l’applicazione con il profumo per capelli for her', 'ALCOHOL, PARFUM (FRAGRANCE), AQUA (WATER), BENZYL SALICYLATE, BUTYL METHOXYDIBENZOYLMETHANE, BENZYL ALCOHOL, HEXYL CINNAMAL, GERANIOL, HYDROXYCITRONELLAL, ETHYLHEXYL METHOXYCINNAMATE, LINALOOL, CINNAMYL ALCOHOL, LIMONENE, BHT, BENZYL BENZOATE, FARNESOL, CITRAL, CITRONELLOL', 'Infiammabile'),
(13, 'For her', 'Eau de Parfum Floreale', 'Il profumo for her è un omaggio alle donne, un dono creato appositamente per loro. \r\nfor her eau de parfum propone un viaggio nel cuore del muschio alla scoperta delle sue molteplici sfaccettature delicate. Il cuore di muschio racchiude l’anima luminosa della fragranza e sviluppa tutta la sua sensualità e la sua sofisticatezza su una trama pastello rosata. La sensazione di pesca e i tocchi di rosa apportano morbidezza, mentre un velo d’ambra dolce e di legno aggiunge mistero e profondità alla composizione.  for her eau de parfum è una fragranza avvolgente, un accordo intimo tra la donna e il suo profumo. for her sprigiona una sorprendente sensazione di armonia a fior di pelle. La sua semplicità e la sua purezza affascinano, il suo mistero intriga, la sua sensualità avvolge. ', 'profumi/Donna/narciso/parfum/fsd.png', 'NARCISO RODRIGUEZ', 'Donna', 'Per un’applicazione coinvolgente e una scia più intensa:\r\n\r\n- Utilizzare il gel doccia for her \r\n\r\n- Applicare la crema corpo for her\r\n\r\n- Applicare il deodorante for her\r\n\r\n- Vaporizzare for her eau de parfum sui punti di pulsazione\r\n\r\n- Sublimare l’applicazione con il profumo per capelli for her', 'ALCOHOL, PARFUM (FRAGRANCE), AQUA (WATER), BENZYL SALICYLATE, BUTYL METHOXYDIBENZOYLMETHANE, LINALOOL, LIMONENE, BENZYL ALCOHOL, CITRONELLOL, HEXYL CINNAMAL, GERANIOL, BHT, CINNAMYL ALCOHOL, HYDROXYCITRONELLAL, BENZYL BENZOATE, FARNESOL, CITRAL', 'Infiammabile'),
(14, 'Acqua di Giò', 'Eau de Toilette', 'ACQUA DI GIÒ EAU DE TOILETTE cattura l’essenza del Mediterraneo. La fragranza si apre con note marine e di bergamotto, che creano la sua iconica freschezza. Il cuore è una miscela di gelsomino, legno di cedro e rosmarino, note aromatiche che evocano il paesaggio mediterraneo. Le note di fondo del profumo, composte da muschi bianchi e patchouli, catturano la forza maschile della fragranza. ACQUA DI GIÒ EAU DE TOILETTE segna l’inizio della fragranza e rimane ancora oggi la sua firma originale. In un nuovo flacone moderno, il flacone conserva il vetro smerigliato, firma della fragranza, che ora passa al vetro trasparente alla base del contenitore.', 'profumi/Uomo/armani/toilette/armanigio.png', 'ARMANI', 'Uomo', 'Nessuna istruzione.', '559270 02 : ALCOHOL • AQUA / WATER / EAU • PARFUM / FRAGRANCE • LINALOOL • LIMONENE • BUTYL METHOXYDIBENZOYLMETHANE • ALPHA-ISOMETHYL IONONE • BENZYL SALICYLATE • GERANIOL • BENZYL ALCOHOL • CITRAL • CITRONELLOL • EUGENOL • CINNAMYL ALCOHOL (F.I.L. N70021801/5).', 'Precauzioni d’uso: infiammabile finche’ non e’ secco. Tenere lontano da fiamme e calore. Evitare di vaporizzare verso gli occhi'),
(15, 'Stronger with You', 'Eau de Toilette', 'Scopri Emporio Armani STRONGER WITH YOU, la fragranza plasmata dall’energia della modernità che celebra l’amore incondizionato e la forza dell’unione".\r\n\r\nGenerosamente maschile, l’uomo STRONGER WITH YOU sperimenta un amore che lo rende più forte. Un amore che rende tutto possibile e diventa una forza motrice sorprendente. Un amore incondizionato che alimenta il desiderio di andare oltre se stessi, di vedere più in grande e più forte.\r\n\r\nImprevedibile, STRONGER WITH YOU vive nel presente e sorprende per la sua originalità, come le note di testa della fragranza: una castagna zuccherata che si unisce a un accordo speziato composto da cardamomo, pepe rosa e foglie di violetta.', 'profumi/Uomo/armani/toilette/stronger.png', 'ARMANI', 'Uomo', 'Vaporizzare il profumo sulla pelle o su un abito rispettando la distanza minima di 10 cm. Creare una nuvola di profumo e attraversarla per una profumazione più delicata. Per una profumazione più decisa, applicare il profumo sui punti di pulsazione: collo, nuca, polso, avambraccio e dietro le orecchi', '947322 08 - INGREDIENTS: ALCOHOL • PARFUM / FRAGRANCE • AQUA / WATER / EAU • LIMONENE • LINALOOL • COUMARIN • DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE • ISOEUGENOL • CITRONELLOL • ALPHA-ISOMETHYL IONONE • EUGENOL • CITRAL • BENZYL ALCOHOL • GERANIOL • CINNAMAL • METHYL 2-OCTYNOATE ', 'PRECAUZIONI D’USO: INFIAMMABILE FINCHE’ NON E’ SECCO. TENERE LONTANO DA FIAMME E CALORE. EVITARE DI VAPORIZZARE VERSO GLI OCCHI\n\nPrecauzioni d’uso: in'),
(16, 'For him bleu noir ', 'Eau de Toilette', 'For him bleu noir eau de toilette è una fragranza elegante, dalle note moderne e dalla scia coinvolgente.  È la prima creazione della linea for him bleu noir di Narciso Rodriguez.\r\n\r\nUN’EAU DE TOILETTE MUSCHIATA E SPEZIATA\r\nQuesta nuova creazione valorizza il cuore di muschio, firma olfattiva del marchio Narciso Rodriguez. In for him bleu noir eau de toilette, le note fresche e speziate unite ai legni sensuali amplificano il mistero del cuore di muschio. \r\n\r\nbleu noir arricchisce la linea for him lasciando un segno indelebile e rafforzandone l’eleganza naturale e moderna e il fascino senza tempo. for him bleu noir è il simbolo dell’uomo moderno, la cui personalità è fatta di contrasti, in parte avvolti dal mistero.  ', 'profumi/Uomo/narciso/toilette.png', 'NARCISO RODRIGUEZ', 'Uomo', 'Per un’applicazione coinvolgente e una scia più intensa: \r\n\r\n- Applicare il deodorante for him.\r\n\r\n- Vaporizzare bleu noir eau de toilette con un gesto ampio sulla pelle, prediligendo i punti di pulsazione e i vestiti. ', 'ALCOHOL, AQUA (WATER), PARFUM (FRAGRANCE), LIMONENE, BUTYL METHOXYDIBENZOYLMETHANE, ETHYLHEXYL METHOXYCINNAMATE, CITRONELLOL, HEXYL CINNAMAL, LINALOOL, COUMARIN, BHT, GERANIOL, CITRAL', 'Infiammabile'),
(17, 'Eros', 'Eau de Parfum\n', 'Una crescita di potenza nell’universo mitico di Versace al maschile che si manifesta senza filtri; un elemento di fascino che mette in superba evidenza amore, passione, bellezza e seduzione. Eros, il dio dell’amore capace di far innamorare con una freccia, raggiunge le sommità appassionate dell’ossessione orientale, da cui emana un desiderio inedito, ai limiti del proibito.\r\n\r\n', 'profumi/Uomo/versace/parfum/vparfum.png', 'VERSACE', 'Uomo', 'Nessuna istruzione.', 'Ingrediente : ALCOHOL DENAT. (SD ALCOHOL 39-C), PARFUM (FRAGRANCE), AQUA (WATER), LIMONENE, LINALOOL, COUMARIN, ALPHA-ISOMETYL IONONE, CITRAL, CITRONELLOL, GERANIOL, CINNAMAL, EUGENOL. vol. 70%""', 'Nessuna avvertenza.'),
(18, 'Tobacco Vanille ', 'Eau de Parfum', 'Tobacco Vanille Eau de Parfum : Un profumo opulento, realizzato con maestrìa artigianale e identificato da note di tabacco e accordi gourmand caldi e dolci.\r\n\r\nOpulento. Caldo. Iconico.\r\nFamiglia olfattiva : Calda e Speziata.\r\n\r\nUn profumo nato dall’affetto che Tom ford nutre per Londra e che ricorda le atmosfere odorose di spezie dei suoi club riservati ai gentlemen.\r\nLo stilista rivisita un genere di fragranza classico arricchendolo con accordi di una cremosa fava tonka, vaniglia, cacao e frutta disidratata abbinati a resina di legni dolci per un effetto moderno, opulento, e quasi inebriante, assolutamente maschile, salvo che sia indossato da una donna.', 'profumi/Uomo/tom ford/parfum.png', 'TOM FORD', 'Uomo', 'Vaporizzare la fragranza una o due volte sulla pelle pulita. Non frizionare la fragranza sulla pelle per non alterare lo sviluppo del profumo.\r\n', 'ALCOHOL DENAT., FRAGRANCE (PARFUM), WATER\\AQUA\\EAU, LINALOOL, BENZYL BENZOATE, GERANIOL, LIMONENE, COUMARIN, CITRONELLOL, EUGENOL, ISOEUGENOL, BENZYL ALCOHOL, CITRAL, CINNAMAL', 'Nessuna avvertenza.'),
(19, 'The Queen of Glow', 'Palette di ombretti', 'The queen of glow\nIl look occhi scintillante più iconico di Charlotte!\nUn trucco da red carpet ispirato a J. Lo che come un raggio di sole illumina e accende lo sguardo!\nQuattro divine e luminose tonalità, bronzo caldo, oro, champagne e rame, create dagli esperti per uno sguardo languido e sensuale.\n\nCosa rende magico questo prodotto:\nTutte le tonalità in questa palette lussuosa hanno una consistenza ricca formulata per scivolare meravigliosamente sulla pelle, catturando la luce per creare l’iconico splendore Tilbury.', 'makeup/1.png', 'CHARLOTTE TILBURY', 'Palette', 'Innanzitutto, usa la tonalità PRIME per impreziosire l’occhio di un color champagne.\nQuindi sfuma la tonalità ENHANCE dorata lungo la palpebra per catturare la luce. Applica la ricca e incantevole tonalità SMOKE sulla piega della palpebra, sulla rima ciliare e sotto l’occhio per ingrandire', 'SHADES: PRIME\r\n\r\nMICA, OCTYLDODECYL STEAROYL STEARATE, TALC, PENTAERYTHRITYL TETRAISOSTEARATE, SYNTHETIC FLUORPHLOGIPITE, CAPRYLYL GLYCOL, PHENOXYETHANOL, MAGNESIUM MYRISTATE, HEXYLENE GLYCOL, DIAMOND POWDER, TIN OXIDE, [+/- TITANIUM DIOXIDE (CI 77891)', 'Nessuna avvertenza.'),
(20, 'Lash Clash', 'Mascara Volume Estremo', 'L’iconico mascara volume estremo Lash Clash, ora disponibile in una nuova shade ultra-couture: Scandalous Green, per un look occhi intenso e audace.\r\nDona al tuo sguardo fino al +200%* di volume estremo. Lash Clash massimizza l’intensità delle ciglia grazie a una texture innovativa che dura fino a 24H*.\r\nLa sua formula è arricchita da pigmenti di colore nero intenso a prova di sbavature. Inoltre, il suo applicatore iconico da 10,5 mm permette di modulare il volume a piacere, da una fino a cinque passate. La sua formula è infusa da estratti nutrienti di Iris Florentia, provenienti dagli Ourika Community Garden di Yves Saint Laurent, che mantengono le ciglia morbidissime e soffici al tatto.', 'makeup/2.png', 'YVES SAINT LAURENT', 'Occhi', '• Applica il mascara dalla base alle punte delle ciglia per un colore ed un volume estremo\r\n• Effettua movimenti a zig zag in orizzontale per evitare l’effetto grumi.\r\n• Per rimuovere il mascara, utilizzare un’acqua micellare detergente', '768958 - INGREDIENTS: AQUA / WATER / EAU • BEHENYL BEHENATE • ETHYLENEDIAMINE/STEARYL DIMER DILINOLEATE • STYRENE/ACRYLATES/AMMONIUM METHACRYLATE COPOLYMER • STEARIC ACID • CI 42090 / BLUE 1 LAKE • CETEARYL ALCOHOL', 'Nessuna precauzione d’uso specifica per questo prodotto in condizioni d’uso normali o prevedibili.\r\n\r\n'),
(21, 'Soft Pinch', 'Blush liquido', 'Il blush liquido Soft Pinch di Rare Beauty è leggero e a lunga tenuta. Il prodotto si fonde perfettamente con la pelle e le dona una delicata e sana luminosità. Il fard è disponibile nel finish mat o perlato.\r\n\r\nGrazie alla sua formula ultra leggera, arricchita di pigmenti a lunga tenuta, questo blush liquido permette di ottenere una luminosità radiosa e sana per tutto il giorno. Il prodotto si fonde perfettamente con la pelle, offrendo una coprenza modulabile con un effetto naturale, come una seconda pelle.\r\nVegan : Prodotti realizzati con ingredienti di origine naturale.', 'makeup/3.png', 'RARE BEAUTY', 'Labbra', 'Come mettere il blush?\r\nRimuovere delicatamente il prodotto in eccesso dall’applicatore.\r\nUtilizzare l’applicatore a piede di capra, deposita uno o due gocce di blush liquido su ogni guancia.\r\nSfumare con la punta delle dita per un risultato uniforme e naturale.', 'HYDROGENATED POLYISOBUTENE, HYDROGENATED POLY(C6-14 OLEFIN), MICA, OCTYLDODECANOL, ETHYLENE/PROPYLENE/STYRENE COPOLYMER, TRIMETHYLSILOXYSILICATE, ISODODECANE, 1,2-HEXANEDIOL, DISTEARDIMONIUM HECTORITE, SORBITAN SESQUIOLEATE, PROPYLENE CARBONATE', 'Nessuna avvertenza'),
(22, 'Detergente allo Squalano ', 'Detergente e Struccante', 'Un detergente delicato che deterge e strucca alla perfezione. La formula contiene squalano e altri esteri lipofili, che eliminano efficacemente trucco ed impurità, lasciando la pelle morbida e idratata. Scaldando il prodotto tra le mani per 10-30 secondi, la sua texture cremosa si trasformerà in olio. L’emulsione dei sucresteri presenti nella formula consente di catturare ed eliminare trucco e impurità durante il risciacquo. Privo di sapone e non comedogeno, questo detergente è formulato per un uso quotidiano e per tutti i tipi di pelle.\r\nVegan : Prodotti realizzati con ingredienti di origine naturale.', 'makeup/4.png', 'THE ORDINARY', 'Detergenti', 'Scaldare una piccola quantità di prodotto tra le mani finché si trasformerà in olio. Applicare sulla pelle asciutta e massaggiare, poi sciacquare con acqua tiepida.\r\nIn caso di irritazione, interrompere l’utilizzo e consultare un medico. Usare esclusivamente su pelle integra, seguendo le istruzioni ', 'SQUALANE, AQUA/WATER/EAU, COCO-CAPRYLATE/CAPRATE, GLYCERIN, ETHYL MACADAMIATE, SUCROSE STEARATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, HYDROGENATED STARCH HYDROLYSATE, SUCROSE LAURATE, POLYACRYLATE CROSSPOLYMER-6, ISOCETETH-20, SODIUM POLYACRYLATE', 'Nessuna avvertenza.'),
(23, 'The Calm Balm', 'Balsamo detergente', '\r\nUn balsamo detergente che scioglie trucco, sebo e impurità mentre nutre e calma la pelle. Ideale per pelli sensibili, lascia il viso pulito, morbido e fresco.\r\nIspirato ai rituali della K-Beauty, questo balsamo delicato ma potente si trasforma in un olio setoso che penetra in profondità nella pelle, eliminando ogni traccia della giornata.\r\nTi farà sciogliere il cuore – e il trucco! La sua formula lenitiva assicura un’esperienza di detersione profonda, senza lasciare residui', 'makeup/5.png', 'YEPODA', 'Detergenti', '1. Riscalda il balsamo tra le dita.\r\n2. Emulsiona sul viso con un po’ d’acqua.\r\n3. Detergi delicatamente il viso con un panno verso l’alto per rimuovere trucco e sebo in eccesso', 'OLEA EUROPAEA (OLIVE) FRUIT OIL, CETEARYL OLIVATE, SUCROSE POLYSTEARATE, COCOS NUCIFERA (COCONUT) OIL, SORBITAN OLIVATE, BUTYROSPERMUM PARKII (SHEA) BUTTER, PROPANEDIOL, AQUA, DECYL GLUCOSIDE, EUPHORBIA CERIFERA (CANDELILLA) WAX, ORYZA SATIVA (RICE) BRAN WAX', 'Nessuna avvertenza.'),
(24, 'Nars Soft Matte Concealer', 'Correttore Antiocchiaie', 'Il correttore Soft Matte Complete Concealer corregge i rossori del viso.\r\nSembra levigare, correggere e minimizzare le imperfezioni, rendendole praticamente invisibili.\r\nIl ritocco perfetto.\r\nOttieni risultati con l’emblematico correttore effetto mat ad alta coprenza di NARS. Combina una correzione ad alte prestazioni all’effetto naturale: il Soft Matte Complete Concealer si sfuma facilmente e sembra levigare l’incarnato disomogeneo mentre minimizza occhiaie, brufoli, rossori e macchie scure. Il suo effetto mat dura tutto il giorno. Con il tempo, questo correttore dona alla pelle un aspetto più morbido e liscio grazie ai peptidi, all’acido ialuronico e al cocktail protettivo di vitamine A, C ed E che contiene. Coprenza con un finish 100% naturale. Senza olio.\r\n', 'makeup/6.png', 'NARS', 'Occhi', 'Grazie alla formula cremosa e leggera, questo correttore antiocchiaie si applica facilmente con le dita e si fonde per un effetto seconda pelle assolutamente naturale.\nConsiglio del makeup artist: se non vuoi usare il fondotinta,  applica l’antiocchiaie Soft Matte CC di Nars', 'TITANIUM DIOXIDE • DIMETHICONE • WATER • GLYCERIN • BUTYLENE GLYCOL • NYLON-12 • PARAFFIN • DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER • DICAPRYLYL CARBONATE • PEG-10 DIMETHICONE • IRON OXIDES • PEG-400 • SILICA', 'Leggi l’interno della confezione.\r\nContiene vitamina A. Prima dell’uso considera il tuo fabbisogno quotidiano.'),
(25, 'Cheeky Cheeks', 'Lip & Cheeks', 'Mini Blush in Stick: luminosità e colore istantanei per labbra e guance dall’aspetto visibilmente più sano.  \r\nLa formula leggera e long-lasting si sfuma con facilità, lasciando un colore uniforme e modulabile, dall’effetto second skin, non oily.  \r\nMetà skincare, metà makeup, gli attivi contenuti rendono la texture sensoriale e performante ma, allo stesso tempo, delicata e rispettosa per il viso.  \r\nIl formato piccolo ed in stick permette un’applicazione semplice e precisa, ovunque tu sia.  ', 'makeup/7.png', 'AUDRER', 'Occhi', 'Applicare con le dita, un pennello o direttamente dallo stick, per poi sfumare delicatamente su labbra e guance. Il colore è modulabile: per un colore più intenso, stratificare il prodotto.', 'OCTYLDODECANOL, LAURYL DIMETHICONE, DIMETHICONE, SYNTHETIC WAX, C20-24 ALKYL DIMETHICONE, C26-28 ALKYL DIMETHICONE, DIMETHICONE/VINYL DIMETHICONE CROSSPOLYMER, SILICA, MICA, DICALCIUM PHOSPHATE', 'Nessuna avvertenza.'),
(26, 'Honey Gold', 'Lip Oil', 'Un olio per labbra che idrata intensamente, infuso di miele Mirsalehi e gli oli del nostro Bee Garden, per una lucentezza a specchio e un finish asciutto. Rivesti le labbra di un velo di colore e del profumo avvolgente dei frutti preferiti delle api.\r\n\r\nCon l’aggiunta di acido ialuronico e oli di semi di jojoba e limnanthes alba, la formula non appiccicosa trattiene l’acqua e leviga le labbra, per un’idratazione che dura tutto il giorno.\r\n\r\nIl miele Mirsalehi proviene dal nostro Bee Garden Gisou nei Paesi Bassi, dove la tradizione di apicoltura di famiglia si tramanda da sei generazioni.', 'makeup/8.png', 'GISOU', 'Labbra', 'Applica semplicemente l’Honey Infused Lip Oil sulle labbra ogni volta che ne senti il bisogno.\r\n\r\nPer risultati ottimali, esfolia le labbra prima dell’applicazione per ottenere un finish ultra liscio, morbido e non appiccicoso.\r\n', 'Polyglyceryl-2 Isostearate/Dimer Dilinoleate Copolymer, Dilinoleic Acid/Propanediol Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Caprylic/Capric Triglyceride, Limnanthes Alba (Meadowfoam) Seed Oil', 'ATTENZIONE: solo per uso esterno. In caso di irritazioni, sospendere l’uso. Tenere fuori dalla portata dei bambini.'),
(27, 'Nabla Close-Up Lip Shaper', 'Matita Labbra', 'La Close-Up Lip Shaper è la matita giusta per valorizzare il volume delle labbra nel modo più realistico possibile. La formula scorrevole e no-transfer offre un corretto bilanciamento tra cremosità e struttura garantendo massimo controllo e precisione mentre la gamma di tonalità nude è studiata appositamente per definire e disegnare le labbra in modo naturale.', 'makeup/9.png', 'NABLA', 'Labbra', 'Per definire la forma delle labbra in modo naturale, applica la Close-Up Lip Shaper più vicina alla tua tonalità, seguendo il contorno. Per un effetto ottico di labbra più voluminose, applica Close-Up Lip Shaper un millimetro fuori dal contorno naturale. ', 'DIMETHICONE, TRIMETHYLSILOXYSILICATE, SYNTHETIC,WAX, BIS-DIGLYCERYLPOLYACYLADIPATE2,PHENYLPROPYLDIMETHYLSILOXYSILICATE,POLYETHYLENE,POLYHYDROXYSTEARIC ACID, DISILOXANE, MICA, CAPRYLYL METHICONE,DISTEARDIMONIUM HECTORITE, DICALCIUM PHOSPHATE', 'Nessuna avvertenza'),
(28, 'Dior Forever ', 'Fondotinta mat 24 h no transfer', 'Scopri il fondotinta Dior Forever, l’icona del make-up Dior no transfer che offre all’incarnato 24 ore(1) di perfezione elevata. Formulato con l’86%(2) di base trattante floreale, questo fondotinta migliora visibilmente la qualità della pelle, giorno dopo giorno.\r\n\r\nL’incarnato appare immediatamente levigato e opacizzato. In una settimana soltanto, la pelle presenta meno zone lucide. In un mese soltanto, i pori appaiono visibilmente affinati.', 'makeup/10.png', 'DIOR', 'Detergenti', 'Questi i consigli di Peter Philips:\r\n1. Comincia ad applicare il fondotinta picchiettando sulle zone che hanno più bisogno di essere corrette.\r\n2. Per coprire in modo perfettamente uniforme tutto il viso, puoi utilizzare un pennello per fondotinta.', '#15866 AQUA (WATER), METHYL TRIMETHICONE, ISODODECANE, ALCOHOL, BUTYLENE GLYCOL, TITANIUM DIOXIDE, PEG-9 POLYDIMETHYLSILOXYETHYL DIMETHICONE, ETHYLHEXYL SALICYLATE, SYNTHETIC FLUORPHLOGOPITE', 'Nessuna avvertenza'),
(29, 'Filmstar Bronze Glow', 'Palette viso', 'La palette per contouring ORIGINALE Filmstar Bronze&Glow ti aiuterà ad affinare, scolpire, ridurre, ridisegnare ed esaltare i lineamenti del viso. Risultato: una pelle da favola. Esalta il tuo viso con uno stile sensazionale!\r\n\r\nCOSA RENDE MAGICA QUESTA PALETTE?\r\n\r\nUn incarnato luminoso è la base perfetta per qualsiasi trucco, è quindi importante avere una carnagione magnifica!\r\nIl bronzer è una combinazione di perle e pigmenti per un ovale scolpito e una pelle baciata dal sole.\r\n\r\nL’illuminante ha una base dorata che esalta qualsiasi carnagione grazie alla tecnologia Light Flex, che cattura e riflette la luce nei punti desiderati.', 'makeup/11.png', 'CHARLOTTE TILBURY', 'Palette', '1. Applica la tonalità "Sculpt" sulle zone che desideri: sull’incavo delle guance, sulle tempie, sulla mandibola e sulla punta del naso.\r\n2. Applica la tonalità "Highlight" nella parte prominente degli zigomi, al centro del naso, sull’arco di cupido e l’arcata sopraccigliare', 'BRONZER TALC, MICA, ORYZA SATIVA (RICE) STARCH, ISONONYL ISONONANOATE, DIMETHICONE, ZEA MAYS (CORN) STARCH, ZINC STEARATE, CAPRYLYL GLYCOL, OCTYLDODECYL STEAROYL STEARATE, PHENOXYETHANOL, DIMETHICONOL', 'Nessuna avvertenza.'),
(30, 'Glazed Plum', 'Lip Oil', 'Un olio per labbra che idrata intensamente, infuso di miele Mirsalehi e gli oli del nostro Bee Garden, per una lucentezza a specchio e un finish asciutto. Rivesti le labbra di un velo di colore e del profumo avvolgente dei frutti preferiti delle api.\r\n\r\nCon l’aggiunta di acido ialuronico e oli di semi di jojoba e limnanthes alba, la formula non appiccicosa trattiene l’acqua e leviga le labbra, per un’idratazione che dura tutto il giorno.', 'makeup/12.png', 'GISOU', 'Labbra', 'Applica semplicemente l’Honey Infused Lip Oil sulle labbra ogni volta che ne senti il bisogno.\r\n\r\nPer risultati ottimali, esfolia le labbra prima dell’applicazione per ottenere un finish ultra liscio, morbido e non appiccicoso.', 'Polyglyceryl-2 Isostearate/Dimer Dilinoleate Copolymer, Dilinoleic Acid/Propanediol Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Caprylic/Capric Triglyceride, Limnanthes Alba (Meadowfoam) Seed Oil', 'ATTENZIONE: solo per uso esterno. In caso di irritazioni, sospendere l’uso. Tenere fuori dalla portata dei bambini.'),
(31, 'Brazilian Bum Bum Cream', 'Crema Corpo Brasiliana', 'Una crema per il corpo a rapido assorbimento che aiuta a rassodare e levigare la pelle.\r\n\r\nMolte creme brasiliane contengono un ingrediente segreto: il guaranà, una pianta originaria dell’Amazzonia, il cui frutto è ricco di una delle forme di caffeina più potenti al mondo.\r\nLa crema brasiliana Bum Bum è potenziata anche da un mix di burro di cupuaçu ultra nutriente, açai potente antiossidante e olio di cocco ultra rivitalizzante, per una pelle irresistibilmente vellutata.\r\n\r\nQuesta texture a rapido assorbimento contiene una piccola quantità di mica, per uno splendore brasiliano perfetto, mentre la formula contribuisce a levigare e a rassodare la pelle del corpo.\r\nPistacchio e caramello profumano delicatamente la pelle.', 'corpo/1.png', 'SOL DE JANEIRO', 'Crema idratante', 'Come si usa?\r\n- Massaggiare con movimenti circolari per riscaldare la zona, promuovere l’assorbimento e stimolare la circolazione.\r\n- Se ne consiglia l’uso su glutei, gambe, addome, braccia e il resto del corpo.', 'Aqua (Water, Eau), Methyl Glucose Sesquistearate, Phenyl Trimethicone, Dodecane, Caprylic/Capric Triglyceride, Glyceryl Stearate Citrate, Parfum (Fragrance), Cetearyl Alcohol, Sodium Hyaluronate, Cocos Nucifera (Coconut) Oil, Euterpe Oleracea', 'Nessuna avvertenza.'),
(32, 'Sundays in Rio Perfume Mist', 'Spray Profumato Corpo', 'In brasiliano essere "cheirosa" significa profumare in modo irresistibilmente buono, ma è anche uno stile di vita di cui ti innamorerai.\r\nLo spray profumato Sundays in Rio celebra l’energia travolgente di una domenica brasiliana. Invitante e vibrante, questa fragranza prolunga le vibrazioni positive con le sue note di vaniglia calda, pepe rosa e muschio ambrato.', 'corpo/2.png', 'SOL DE JANEIRO', 'Profumi corpo', 'Nebulizza lo spray profumato dalla testa ai piedi, dove e quando vuoi. (Attenzione, potrebbero piovere complimenti!)', 'Alcohol Denat., Aqua (Water, Eau), Parfum (Fragrance), Benzyl Benzoate, Citronellol, Hydroxycitronellal.\r\n', 'Nessuna avvertenza.'),
(33, 'Brazilian Body Fragrance ', 'Spray Corpo Formato Viaggio', 'Le donne brasiliane ricorrono a tutti i sensi per piacere.\r\n\r\nUno dei loro grandi segreti di bellezza è essere “cheirosa” (scie-ró-sa), che significa essere deliziosamente profumate, dall’alba al tramonto. Ispirato alle note inebrianti di pistacchio e caramello al burro salato della crema Brazilian Bum Bum, lo spray profumato per il corpo Brazilian Crush ti trasporta immediatamente sulle calde spiagge di Rio de Janeiro.\r\n', 'corpo/3.png', 'SOL DE JANEIRO', 'Profumi corpo', 'Nessuna istruzione.', 'Alcohol Denat., Aqua (Water, Eau), Parfum (Fragrance), Coumarin, Citronellol, Benzyl Salicylate, Hydroxycitronellal, Benzyl Alcohol, Benzyl Benzoate.', 'Nessuna avvertenza.'),
(34, 'The Ritual of Karma ', 'Olio corpo illuminante', 'Per una pelle luminosa, usa l’olio corpo illuminante di The Ritual of Karma.\r\n\r\nL’olio di origine naturale al 96% ammorbidisce la pelle con una miscela di oli di jojoba, oliva e cartamo.\r\n\r\nSi lascia assorbire rapidamente, ammorbidisce e ravviva la pelle opaca, mentre un sottile luccichio di particelle minerali iridescenti dona un aspetto raggiante e luminoso.\r\n\r\nL’olio illuminante sprigiona il profumo delicato del tè bianco e del fiore di loto.', 'corpo/4.png', 'RITUALS', 'Olio', 'Agitare bene prima dell’uso.\r\n\r\nApplicalo subito dopo la doccia.\r\n\r\nLascia che si assorba e si asciughi per 5 minuti prima di vestirti.', 'Caprylic/Capric Triglyceride, Polyamide-8, Carthamus Tinctorius (Safflower) Seed Oil, Olea Europaea (Olive) Fruit Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Camellia Sinensis (White Tea) Leaf Extract, Nelumbo Nucifera (Lotus) Flower Extract', 'Nessuna avvertenza.'),
(35, 'Fattori naturali di idratazione', 'Lozione per il corpo', 'Una lozione per il corpo leggera e non grassa, per un’idratazione superficiale immediata e per tutto il giorno.\\tLa Lozione Corpo - Fattori naturali di idratazione + inulina è una crema idratante per il corpo dalla texture leggera per tutti i tipi di pelle, formulata per mantenere la pelle idratata anche dopo la detersione. La formula simile a una lozione fornisce un’idratazione istantanea per tutto il giorno e rafforza la barriera cutanea in una sola applicazione.\r\n\r\nLa Lozione per il corpo - Fattori naturali di idratazione + inulina fornisce fattori idratanti naturali identici a quelli presenti nella pelle, come urea, PCA e aminoacidi. Questi ingredienti agiscono come umettanti (molecole che amano l’acqua), che attirano e trattengono l’acqua per mantenere la pelle idratata.\r\n', 'corpo/5.png', 'THE ORDINARY', 'Trattamenti corpo', 'Applicare sul corpo secondo necessità.\r\n\r\n', 'Aqua (Water), Caprylic/Capric Triglyceride, Glycerin, Inulin, Propanediol, Isodecyl Neopentanoate, Arachidyl Alcohol, Rhus Succedanea Fruit Wax, Sodium Hyaluronate, Arginine, Glycine, Alanine, Serine, Proline, Threonine, Glutamic Acid, Lysine HCl, Betaine, Sodium PCA, PCA', 'Nessuna avvertenza.'),
(36, 'Neroli Portofino', 'Crema Mani', 'Setosa e profumata, questa crema mani completa l’esperienza Neroli Portofino, donando un’incredibile morbidezza alla pelle e un’idratazione duratura. Grazie alla formula arricchita con glicerina, acido ialuronico e caffeina, la pelle appare idratata e rivitalizzata, per un effetto radioso. Modalità di utilizzo: Applicare sul palmo delle mani, massaggiando per permettere l’assorbimento.', 'corpo/6.png', 'TOM FORD', 'Crema mani', 'Nessuna istruzione.', 'WATER\\AQUA\\EAU, OCTYLDODECYL MYRISTATE, BUTYLENE GLYCOL, TRICAPRYLIN, GLYCERIN, BEHENYL ALCOHOL, HEXYLDECYL STEARATE, DIMETHICONE, PEG-100 STEARATE, FRAGRANCE (PARFUM), HYDROGENATED LECITHIN, NEOPENTYL GLYCOL DIHEPTANOATE, ALOE BARBADENSIS ', 'Nessuna avvertenza.'),
(37, 'Find Comfort Hand Cream', 'Crema mani idratante', 'Una crema mani dalla fragranza inebriante, che penetra rapidamente e fornisce fino a 16 ore di idratazione, ammorbidendo la pelle con la sua texture fresca e non grassa.\r\n\r\nProfumata con note di scorza di limone frizzante, gelsomino e legno di cashmere, questa crema mani nutriente idrata per tutto il giorno, anche dopo aver lavato le mani, ammorbidendo le cuticole. Il flacone smart anti-spreco si apre facilmente con una sola rotazione e il tappo rimane saldamente in posizione per non perderlo.', 'corpo/7.png', 'RARE BEAUTY', 'Crema mani', 'Girare una volta per aprire. Applicare generosamente massaggiando su tutto il corpo fino a completo assorbimento. Utilizzare mattina e sera, o quando necessario, soprattutto dopo aver lavato le mani.', 'Water (Aqua/Eau), Glycerin, Cetearyl Alcohol, Macadamia Integrifolia Seed Oil, Butyrospermum Parkii (Shea) Butter, Niacinamide, Pentaerythrityl Tetraethylhexanoate, Silica, Polyglyceryl-3 Methylglucose Distearate, 1,2-Hexanediol, Pentylene Glycol', 'Nessuna avvertenza.'),
(38, 'Delicia Drench™ Body Butter', 'Burro per il corpo', 'Delicia Drench™ Body Butter: la nuova crema per il corpo Sol de Janeiro a rapido assorbimento, per un’idratazione di lunga durata.\r\n\r\nQuesto burro per il corpo dal finish vellutato preserva a lungo l’idratazione, riparando la barriera protettiva della pelle e migliorando il microbioma.', 'corpo/8.png', 'SOL DE JANEIRO', 'Trattamenti corpo', 'Massaggiare su tutto il corpo, specialmente sulle zone più secche. Lasciare che la pelle assorba il prodotto per godere appieno dei suoi benefici nutrienti. Utilizzare tutti i giorni per ottenere risultati ottimali.', 'qua (Water, Eau), Butyrospermum Parkii (Shea) Butter, Cocos Nucifera (Coconut) Oil, Ethylhexyl Palmitate, Parfum (Fragrance), Methyl Glucose Sesquistearate, Glyceryl Stearate SE, Lauryl Laurate, Glycerin, Myristyl Myristate, Hydrolyzed Sodium Hyaluronate (Hyaluronic Acid)', 'Nessuna avvertenza.\r\n'),
(39, 'Dior Solar', 'Latte Protettivo SPF 30', 'Dior Solar Il Latte Protettivo per Viso e Corpo SPF 30 è un latte solare che si diffonde in modo pratico e intuitivo: grazie al suo formato spray, questo latte-in-brume resistente all’acqua si applica sulle aree del corpo che hanno bisogno di essere protette in modo omogeneo.\r\n\r\nLa texture lattiginosa e impercettibile al tatto del latte possiede una profumazione gradevole. La pelle è idratata e valorizzata da un velo luminoso e satinato e, insieme, risulta protetta dai raggi UVA/UVB e dalle aggressioni esterne.\r\n\r\nDior Solar Il Latte Protettivo per Viso e Corpo SPF 30 avvolge la pelle in una sensazione di freschezza. Utilizzo dopo utilizzo, l’abbronzatura diventa più bella e più uniforme.', 'corpo/9.png', 'DIOR', 'Solari', 'Facile da applicare grazie a uno spray che consente di distribuire uniformemente il latte solare sulla pelle, Dior Solar Il Latte Protettivo per Viso e Corpo SPF 30 protegge dai raggi UVA/UVB e, simultaneamente, valorizza l’abbronzatura.', '#18274 AQUA (WATER),BUTYLENE GLYCOL DICAPRYLATE/DICAPRATE,DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE,ALCOHOL,DIISOPROPYL SEBACATE,TRIAZONE,PROPANEDIOL,ETHYLHEXYL SALICYLATE,BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE,PHENYLBENZIMIDAZOLE SULFONIC', 'Precauzioni d’uso: Applicare generosamente prima dell’esposizione al sole e riapplicare frequentemente, specialmente dopo il contatto con l’acqua.'),
(40, 'Rio Radiance SPF50 ', 'Spray Corpo SPF50', 'Una luminosità naturale. Questo spray per il corpo Rio Radiance SPF50 di Sol de Janeiro rinfresca e idrata la pelle. Lasciati sedurre dal nostalgico profumo estivo del sole sulla pelle.\r\n\r\nIngredienti chiave:\r\n- Niacinamide\r\n- Estratto di semi di pongamia\r\n- Estratto di pitanga\r\n- Acqua di cocco', 'corpo/10.png', 'SOL DE JANEIRO', 'Solari', 'Applica una dose generosa in modo uniforme 15 minuti prima dell’esposizione al sole.', 'Alcohol Denat., Octocrylene, Butyloctyl Salicylate, Ethylhexyl Salicylate, Butyl Methoxydibenzoylmethane, Parfum (Fragrance), Acrylates/Octylacrylamide Copolymer, Polyester-8, Ethylhexyl Methoxycrylene, Diheptyl Succinate, Capryloyl Glycerin/Sebacic Acid Copolymer, Ethyl Ferulate, Niacinamide', 'Nessuna avvertenza.'),
(41, 'Intense Nourishment', 'Balsamo corpo', 'Il balsamo per il corpo di Moroccanoil è una crema idratante ricca di olio d’argan antiossidante e burro di karitè, mango e cocco che si fonde a contatto con la pelle per nutrirla e ammorbidirla a fondo. L’acido ialuronico attira e preserva l’idratazione. Infuso dell’iconica fragranza Moroccanoil.\r\n', 'corpo/11.png', 'MOROCCANOIL', 'Trattamenti corpo', 'Istruzioni per l’uso:\r\n\r\n- Massaggiare sulla pelle asciutta e pulita, insistendo sulle parti ruvide.', 'AQUA/WATER/EAU, C12-15 ALKYL BENZOATE, OCTYLDODECANOL, GLYCERIN, GLYCERYL STEARATE, CAPRYLIC/CAPRIC TRIGLYCERIDE, ISOCETYL STEARATE, ISOPROPYL PALMITATE, MANGIFERA INDICA (MANGO) SEED BUTTER, MYRISTYL MYRISTATE, CETEARYL ALCOHOL, ARGANIA SPINOSA (ARGAN) KERNEL OIL, PERSEA GRATISSIMA (AVOCADO) OIL', 'Solo per uso esterno. Evitare il contatto con gli occhi durante l’uso del prodotto. Se necessario, risciacquare accuratamente con acqua.'),
(42, 'Original Fragrance', 'Crema per le mani', 'Una crema nutriente per mani e cuticole. La combinazione di olio di argan ricco di antiossidanti e di burri di cacao e di karité idrata intensamente, mentre l’acido ialuronico aiuta a mantenere l’idratazione. Questa formula non grassa si assorbe immediatamente. Profumato con la fragranza originale Moroccanoil®.', 'corpo/12.png', 'MOROCCANOIL', 'Crema mani', 'Applicare una piccola dose di crema su mani e cuticole ogni giorno, con la frequenza necessaria.', 'AQUA/WATER/EAU, ETHYLHEXYL PALMITATE, CETYL ALCOHOL, GLYCERIN, CETEARETH-20, HYDROXYPROPYL STARCH PHOSPHATE, GLYCERYL STEARATE, PROPANEDIOL, CETEARYL ALCOHOL, PARFUM/FRAGRANCE, ARGANIA SPINOSA (ARGAN) KERNEL OIL', 'ATTENZIONE: Seguire le istruzioni per l’uso. Solo per uso esterno. Evitare il contatto con gli occhi. In caso di irritazioni, sospendere l’uso.'),
(43, 'Protettore assoluto', 'Termoprotettore', 'Il protettore assoluto di Moroccanoil è uno spray termoprotettore che aiuta a mantenere i capelli lucenti, proteggendoli dal calore di phon e piastre.\r\n\r\nQuesto prodotto di styling essenziale, infuso con olio d’argan, può essere usato da solo o insieme ad altri prodotti di messa in piega.\r\n\r\nGrazie alla sua speciale applicazione sotto forma di spray secco, può essere usato sui capelli asciutti o bagnati prima di usare gli strumenti a caldo.\r\nProtegge i capelli dall’aggressione degli strumenti a caldo fino a 230°C (450°F).', 'capelli/other/6.png', 'MOROCCANOIL', 'Temoprotettori', '- Sui capelli umidi: nebulizza generosamente e uniformemente a 15 cm di distanza. Pettina e asciuga. Realizza l’acconciatura con gli strumenti a caldo.\r\n- Sui capelli asciutti: nebulizza generosamente e uniformemente a 15 cm di distanza. Prosegui con una piastra lisciante o un ferro arricciacapelli.', 'DIMETHYL ETHER, SD ALCOHOL 40-B (ALCOHOL DENAT.), AQUA/WATER/EAU, BUTYLENE GLYCOL, OCTYLACRYLAMIDE/ACRYLATES/ BUTYLAMINOETHYL METHACRYLATE COPOLYMER, ARGANIA SPINOSA (ARGAN) KERNEL OIL, ACHILLEA MILLEFOLIUM (COMMON YARROW) EXTRACT', 'AVVERTENZA: PRODOTTO ESTREMAMENTE INFIAMMABILE. Non spruzzare negli occhi. Contenuto sotto pressione. '),
(44, 'Dream Coat', 'Termoprotettore Spray Prodigioso', 'Spray Dream Coat è la chiave per capelli "effetto specchio" lucidi, lucenti e resistenti all’umidità. Il rivoluzionario spray ultraleggero (per tutti i tipi di capelli) che non lascia depositi e non unge i capelli. Ispirato alla tecnologia tessile, il polimero attivato dal calore comprime, stringe e sigilla ogni filo con un "cappuccio impermeabile". Trasforma la texture, aggiunge una lucentezza soprannaturale e la rende immediatamente setosa. Il potente potere antiumidità dura fino a 3 shampoo. Accelera il tempo di asciugatura. Devi vederlo per crederci!', 'capelli/other/7.png', 'COLOR WOW', 'Temoprotettori', 'Dopo il rituale di shampoo / balsamo, dividi i capelli tamponati in piccole sezioni. Spruzzare generosamente e in modo uniforme sui capelli umidi (non bagnati). Dream Coat dovrebbe essere l’ultimo prodotto applicato sui capelli bagnati. Per ottenere i migliori risultati, applicare ogni 3 shampoo.', 'Aqua/Water/Eau, Dipropylene Glycol, Polysilicone-29, DMDM Hydantoin, Propylene Glycol, Glycerin, Silicone Quaternium-18, Butylene Glycol, Iodopropynyl Butylcarbamate, Trideceth-7, Trideceth-12, Phenoxyethanol, Chamomilla Recutita (Matricaria) Flower Extract ', 'Nessuna avvertenza.'),
(45, 'Honey Gloss Ceramide Therapy', 'Maschera Capelli', 'Una maschera per capelli che offre un trattamento dai benefici clinicamente provati. A base di miele dal giardino Mirsalehi e ceramidi, idrata intensamente i capelli, li rinforza e li fa risplendere, senza appesantirli.\r\n\r\nTest clinici lo dimostrano. Questa maschera lascia i capelli luminosi e sani. A base di ceramidi riparatrici, miele di Mirsalehi che dona lucentezza e acido ialuronico idratante, agisce come un trattamento express per i capelli! La texture ricca ma leggera liscia la fibra capillare e aggiunge lucentezza, per capelli più forti, morbidi e intensamente idratati.', 'capelli/other/8.png', 'GISOU', 'Maschere', 'ISTRUZIONI PER L’USO:\r\n- Dopo lo shampoo, tampona i capelli e applica generosamente il prodotto dalle lunghezze alle punte.\r\n- Lascia agire per 5-7 minuti, quindi risciacqua con abbondante acqua.\r\n- Formula abbastanza leggera da poter essere usata a ogni lavaggio.', 'Aqua (Water/Eau), Cetearyl Alcohol, Behenamidopropyl Dimethylamine, Dicocoylethyl Hydroxyethylmonium Methosulfate, Butyrospermum Parkii (Shea) Butter, Lactic Acid, Mel (Honey/Miel)* , Propolis Cera (Propolis Wax/Cire de Propolis)*, Ceramide NP, Hydrolyzed Sodium Hyaluronate, Sodium Hyaluronate', 'Nessuna avvertenza.');
INSERT INTO `prodotto` (`IDprodotto`, `nome`, `didascalia`, `descrizione`, `URLimmagine`, `marca`, `sottocategoria`, `istruzioni`, `ingredienti`, `avvertenze`) VALUES
(46, 'Honey Infused Hair Oil', 'Olio per capelli multifunzione', 'Arricchito con Miele di Mirsalehi dalle fonti sostenibili del Mirsalehi Bee Garden.\r\n\r\nIl miele dona una lucentezza naturale ai capelli. È il prodotto ideale per avere una chioma più sana, morbida e folta.\r\nQuesto olio per capelli multiuso può essere usato come trattamento idratante e nutriente o durante lo styling come step finale. Associalo alla maschera e primer per capelli per avere un effetto ancora più nutriente.\r\n\r\nI SUOI BENEFICI: ripristina e ripara i capelli secchi e danneggiati, nutre e idrata i capelli, riduce l’effetto crespo e previene le doppie punte.', 'capelli/other/9.png', 'GISOU', 'Oli', 'Il prodotto può essere applicato prima dello styling per nutrire i capelli e donare lucentezza.\r\nApplicare da 1 a 2 gocce (a seconda della lunghezza e dello spessore dei capelli).', 'Dimethicone, Dimethiconol, Trisiloxane, Mel (Honey / Miel)*, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Cocos Nucifera (Coconut) Oil, Argania Spinosa Kernel Oil, Passiflora Incarnata Seed Oil', 'Nessuna avvertenza.'),
(47, 'Acidic Color Gloss', 'Termoprotettore per capelli colorati', 'Trattamento spray senza risciacquo per capelli colorati. Grazie alla sua tecnologia protettiva invisibile e la sua formula a pH acido, protegge dal calore fino a 230°C e dagli aggressori esterni. Migliora la districabilità, idrata e rende i capelli più morbidi e luminosi. BENEFICI CHIAVE: - Protegge dal calore fino a 230°* - Capelli 13x più morbidi* - Migliora immediatamente la districabilità* - 6X boost di idratazione* - Aiuta a trattenere il colore e previene i danni *Test strumentale ACG Trattamento senza risciacquo vs. shampoo non condizionante', 'capelli/other/10.png', 'REDKEN', 'Temoprotettori', 'Vaporizzare su capelli puliti e tamponati. Non risciacquare. In caso di contatto con gli occhi, risciacquare immediatamente.', 'AQUA / WATER / EAU • DIMETHICONE • STEARYL ALCOHOL • BEHENTRIMONIUM CHLORIDE • TRIDECETH-9 PG-AMODIMETHICONE • PHENOXYETHANOL • POLYSORBATE 20 • PARFUM / FRAGRANCE • ISOPROPYL ALCOHOL • PPG-5-CETETH-20 • LAURETH-23 • LAURETH-4 • TRIDECETH-12', 'Non sono necessarie precauzioni specifiche per l’uso di questo prodotto in condizioni normali o ragionevolmente prevedibili di utilizzo.'),
(48, 'AirWash shampoo secco', 'Shampoo a secco', 'Shampoo secco biotecnologico in formato non aerosol che garantisce una pulizia efficace, riducendo l’eccesso di sebo ed eliminando i cattivi odori senza accumuli e senza lasciare residui bianchi.\r\n\r\nUna nuova generazione di shampoo secco. Il futuro in fatto di cura dei capelli, alimentato dalle biotecnologie. Questa formula riequilibra il sebo nel tempo e promuove la salute del cuoio capelluto.\r\n\r\nRisultati clinicamente testati: il prodotto elimina gli odori e riduce il sebo. Azione continua fino a 3 giorni*. Testato con una singola applicazione su capelli non lavati per 4 giorni.', 'capelli/other/11.png', 'K18', 'Shampoo a secco', 'AGITARE BENE. La formula in formato non aerosol può sembrare leggermente umida, ma non intacca la piega. Tenere il flacone a 10-15 cm dal cuoio capelluto per distribuire in modo uniforme il prodotto.', 'Water (Aqua) (Eau), Alcohol Denat., Silica, Tetraselmis Suecica Extract, Arginine, Lactic Acid, Sodium Hyaluronate, Glycerin, Mannitol, Gellan Gum, Hydrolyzed Hyaluronic Acid, Sodium Phytate, Tromethamine', 'Nessuna avvertenza.'),
(49, 'Blond Absolu Cicaflash ', 'Balsamo per capelli biondi', 'Questo gel opalescente lattiginoso con una leggera colorazione lavanda offre il potere trattante di una maschera con la leggerezza di un balsamo. Ripara i capelli sensibilizzati, nutrendo la fibra. La combinazione di Acido Ialuronico e Stella Alpina ammorbidisce e rafforza i capelli decolorati, fornendo intensa nutrizione. Ideale per tutte le tonalità di faux-blonde, Cicaflash ripara la fibra del capello, limitando rottura ed erosione. Il capello è soffice e idratato e al tempo stesso rimane leggero e luminoso.', 'capelli/other/12.png', 'KERASTASE', 'Trattamenti Capelli', 'FASE 1 Applicare sui capelli lavati e tamponati. Massaggiare le lunghezze e le punte. \r\nFASE 2 Lasciare in posa da 3 a 5 minuti. \r\nFASE 3 Risciacquare. \r\nIn caso di contatto con gli occhi, sciacquare immediatamente e abbondantemente.', '1199753 B - INGREDIENTS: AQUA / WATER / EAU • CETEARYL ALCOHOL • AMODIMETHICONE • HYDROXYPROPYL STARCH PHOSPHATE • ISOPROPYL MYRISTATE • BEHENTRIMONIUM CHLORIDE • PHENOXYETHANOL • TRIDECETH-5 • ISOPROPYL ALCOHOL • TRIDECETH-6 ', 'In caso di contatto con gli occhi, sciacquarli immediatamente e abbondantemente.\r\n\r\n'),
(50, 'Water Sleeping Mask', 'Maschera notte idratante', 'Scopri la maschera viso idratante che agisce durante la notte! Che cos’è? Questa maschera per il viso idrata, illumina e ammorbidisce la pelle, agendo durante il sonno grazie a un potente complesso derivato da probiotici e squalene. Cosa c’è nella formula? Il complesso derivato da probiotici rafforza la barriera di idratazione della pelle, proteggendola dagli aggressori esterni e potenziandone la luminosità durante la notte! Lo squalane riproduce i naturali lipidi della pelle, per offrire un’idratazione intensa in una texture leggerissima! Il risultato? La pelle stanca ritrova luminosità, uniformità ed è intensamente idratata nello spazio di una notte!', 'viso/1.png', 'LANEIGE', 'Idratanti', 'Applicare uniformemente sul viso. Lasciare agire durante la notte e risciacquare il mattino dopo.', 'WATER / AQUA / EAU, BUTYLENE GLYCOL, GLYCERIN, TREHALOSE, METHYL TRIMETHICONE, 1,2 HEXANEDIOL, SQUALANE, PHENYL TRIMETHICONE, PCA DIMETHICONE, CAPRYLYL METHICONE, AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER, LACTOBACILLUS FERMENT LYSATE', 'Nessuna avvertenza.'),
(51, 'Fat Water', 'Tonico alla niacinamide e ciliegia ', 'Il tonico-siero 2-in-1 Fat Water di Fenty Skin minimizza l’aspetto dei pori dilatati e aiuta a contrastare visibilmente le macchie scure sulla pelle, leviga e riduce la lucidità - tutto senza aggredire la pelle.\r\n\r\nL’efficacia di un siero viso unita all’azione di un tonico in un unico gesto anti-pori. Restringe i pori, aiuta a ridurre visibilmente le macchie scure, leviga e rimpolpa la pelle e riduce la lucidità, senza compromettere l’idratazione. Prodotto adatto a tutti i tipi di pelle (pelle mista, secca, sensibile...).\r\n\r\nI benefici di prodotto:\r\n- Una riserva d’acqua dalla texture densa che restringe l’aspetto dei pori, illumina e leviga la pelle\r\n- La niacinamide agisce sui pori dilatati e uniforma visibilmente il tono dell’incarnato\r\n- Idrata e nutre; lascia la pelle rimpolpata e rigenerata\r\n- Densa e rapida: la texture unica si assorbe all’istante\r\n- Profumo leggero di ciliegia dolce e fico scaldato dal sole', 'viso/2.png', 'FENTY SKIN', 'Tonico', 'Usa il prodotto giorno e notte sulla pelle pulita e asciutta. Applica sui palmi e tampona sul viso, lasciandolo assorbire. Se lo usi di giorno, applica quindi la crema idratante Hydra Vizor. Se lo usi la sera, applica la crema notte Instant Reset.', 'AQUA/WATER/EAU, HAMAMELIS VIRGINIANA (WITCH HAZEL) WATER, BUTYLENE GLYCOL, NIACINAMIDE, POLYSORBATE 20, LEUCONOSTOC/RADISH ROOT FERMENT FILTRATE, BACKHOUSIA CITRIODORA LEAF EXTRACT, CAMELLIA OLEIFERA LEAF EXTRACT', 'Solo per uso esterno.\r\nSeguire le istruzioni.'),
(52, 'Relief Sun SPF50', 'Crema solare al riso e probiotici', 'Relief Sun è una protezione solare biologica leggera e cremosa, piacevole sulla pelle. Anche applicandola più volte in quantità elevata, non risulta mai appiccicosa e lascia la pelle idratata, come una crema idratante leggera.\r\nCon il 30% di estratto di riso e di estratti di cereali fermentati, fornisce idratazione e nutrimento alla pelle.', 'viso/3.png', 'BEAUTY OF JOESON', 'Creme solari', 'Applicare una quantità adeguata di crema solare come ultimo step della routine di skincare per proteggere le aree esposte ai raggi UV.', 'AQUA, DIBUTYL ADIPATE, PROPANEDIOL, DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE, POLYMETHYLSILSESQUIOXANE, ETHYLHEXYL TRIAZONE, NIACINAMIDE, METHYLENE BIS-BENZOTRIAZOLYL TETRAMETHYLBUTYLPHENOL, COCO-CAPRYLATE/CAPRATE', 'Solo per uso esterno. Evitare il contatto con gli occhi. Tenere fuori dalla portata dei bambini.'),
(53, 'Génifique', 'Crema Viso Attivatrice di Giovinezza', 'Scopri una pelle visibilmente ringiovanita in soli 7 giorni!\r\nSe hai una pelle spenta, con segni di espressione o rughe e mancanza di elasticità, la Crema viso anti-età Génifique ti aiuterà a ritrovare una pelle luminosa e dall’aspetto più giovane.\r\nGrazie alla sua texture straordinariamente vellutata e arricchita con attivi leviganti, questa crema viso anti-età offre un’idratazione intensa e lascia sulla pelle una straordinaria sensazione di morbidezza.\r\nI segni dell’età appariranno visibilmente migliorati, i segni di espressione attenuati.\r\nRitrova giorno dopo giorno una pelle che risplende di giovinezza grazie a Génifique Crema, un trattamento da applicare tutti i giorni.', 'viso/4.png', 'LANCOM', 'Antietà', 'Applicare Génifique Crema ogni giorno dopo il siero Advanced Génifique Attivatore di Giovinezza.\r\nPer un contorno occhi visibilmente più giovane, completa la tua routine con Advanced Génifique Yeux Light-Pearl™ Attivatore di giovinezza.', '762215 49 - INGREDIENTS: AQUA / WATER / EAU • GLYCERIN • DIMETHICONE • HYDROGENATED POLYISOBUTENE • BORON NITRIDE • ZEA MAYS STARCH / CORN STARCH • ADENOSINE • BIFIDA FERMENT LYSATE • FAEX EXTRACT / YEAST EXTRACT / EXTRAIT DE LEVURE', 'In caso di contatto con gli occhi, sciacquarli immediatamente e abbondantemente.'),
(54, 'Skin Hero Peeling', 'Peeling Levigante In 2 Minuti', 'SKIN HERO PEELING trasforma la vostra pelle in soli 2 minuti!\r\n\r\nQuesto peeling levigante per il viso:\r\n- Ristruttura la pelle affinando la texture e rimuovendo le cellule morte\r\n- Leviga le linee sottili e la grana della pelle\r\n- Riduce visibilmente i pori e le imperfezioni\r\n\r\nIl risultato? La bellezza della tua pelle nuda viene immediatamente esaltata, appare rinnovata e l’incarnato è unificato!\r\n\r\nIl cuore della nostra formula è il complesso di Ginseng Bianco e un magico cocktail di acidi naturali, AHA, BHA e PHA.', 'viso/5.png', 'ERBORIAN', 'Peeling', 'Applicare sul viso pulito e asciutto uno strato sottile e uniforme, evitando il contorno occhi e labbra.', 'AQUA/WATER, GLYCERIN, GLUCONOLACTONE, GLYCOLIC ACID, ARGININE, METHYLPROPANEDIOL, 1,2-HEXANEDIOL, LACTIC ACID, SODIUM LACTATE, SORBITAN ISOSTEARATE, PANTHENOL, BUTYLENE GLYCOL, SORBITAN STEARATE, PANAX GINSENG ROOT EXTRACT, GLYCYRRHIZA GLABRA', 'Il nostro Skin Hero Peeling è stato clinicamente testato sotto controllo dermatologico su tutti i tipi di pelle.'),
(55, 'Benefiance ', 'Crema Antietà Levigante', 'Benefiance Wrinkle Smoothing Cream appartiene alla linea Shiseido Benefiance. Una crema viso antietà che rinnova la vitalità interna e risveglia i recettori cutanei.\r\nIspirata alla neuroscienza, la ReNeura Technology+™ aiuta a risvegliare i recettori sensoriali che si indeboliscono nel tempo, rendendo la pelle altamente reattiva ai benefici dello skincare.\r\n\r\nCrema viso antietà setosa e idratante, che rende la pelle più reattiva allo skincare antietà, offrendo un aspetto giovane e radioso.\r\nBenefiance Wrinkle Smoothing Cream per tutti i tipi di pelle agisce su rughe, secchezza e perdita di elasticità per un aspetto giovane e radioso. \r\nUna crema antietà effiace:\r\nPelle visibilmente più liscia e idratata con rughe rimpolpate e texture elastica.', 'viso/6.png', 'SHISEIDO', 'Antietà', '-Usare ogni mattina e sera dopo aver deterso e riequilibrato la pelle.\r\n-Stenderla delicatamente sul viso iniziando dalle zone più ampie, come guance e fronte.', 'WATER(AQUA/EAU), CETYL ETHYLHEXANOATE, GLYCERIN, NIACINAMIDE, NYLON-12, CETEARYL ALCOHOL, DIPROPYLENE GLYCOL, ALCOHOL, CAPRYLIC/CAPRIC TRIGLYCERIDE, PHYTOSTERYL MACADAMIATE, GLYCERYL STEARATE, DIMETHICONE, DIISOSTEARYL MALATE', 'Nessuna avvertenza.\r\n'),
(56, 'Repair Sunscreen', 'Crema solare riparatrice SPF50+', 'Proteggi e ripara la pelle con la crema solare riparatrice SPF50+, un’emulsione dalla consistenza leggera che offre un’elevata protezione contro i raggi UVA e UVB, la luce blu e la luce visibile. Inoltre, aiuta a riparare la pelle danneggiata dal sole e a ridurre gli arrossamenti. \r\n\r\nIl 100% di chi l’ha testata afferma che lascia la pelle appare idratata, sana e liscia* grazie ai potenti principi attivi contenuti nella crema, tra cui l’1% di estratto di cellule vegetali di cotone. Questo principio attivo ha il potere di lenire la pelle e ridurre il rossore associato all’esposizione al sole. La niacinamide al 3% aiuta a bilanciare il tono della pelle, a regolare la produzione di sebo e a minimizzare la perdita di acqua transepidermica. Il complesso ialuronico multi-molecolare e il pantenolo idratano e preparano la pelle a diversi livelli, così come il complesso NAC Y2 in dose riparatrice.\r\n', 'viso/7.png', '111SKIN', 'Creme solari', 'Applicare uno strato generoso e uniforme di prodotto su viso e collo, dopo la crema idratante e prima del trucco, 15-20 minuti prima dell’esposizione al sole.', 'Aqua, Dibutyl Adipate, Octocrylene, Butyl Methoxydibenzoylmethane, Ethylhexyl Salicylate, Niacinamide, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Phenylbenzimidazole Sulfonic Acid, Ethylhexyl Triazone, Cetearyl Alcohol, Propanediol, Silica, Aminomethyl Propanol, Panthenol', 'Nessuna avvertenza.'),
(57, 'Red Pepper Super Sérum', 'Siero energizzante', 'In Erborian, ci fidiamo così tanto dei nostri super ingredienti coreani che abbiamo dato loro un posto speciale nel nostro flacone: i loro estratti sono incorporati all’80%.\r\n\r\nRED PEPPER SUPER SERUM agisce come una dose energizzante che risveglia la pelle, per aumentare istantaneamente la sua naturale luminosità. In superficie, i suoi agenti esfolianti di origine naturale rivelano un colorito più uniforme e luminoso. La promessa di una pelle rigenerata, tonica e ricca di salute; in una texture fluida e leggera!\r\nCos’altro? Un prebiotico, per aiutare a mantenere l’equilibrio della pelle e preservare così la sua idratazione.\r\n', 'viso/8.png', 'ERBORIAN', 'Sieri ', 'Applicare sul viso mattina e sera, prima della routine quotidiana.\r\nAl primo utilizzo, attivare l’erogatore più volte per attivarlo.', 'CAPSICUM ANNUUM LEAF EXTRACT , PROPANEDIOL , AQUA/WATER , GLUCONOLACTONE , 1,2,HEXANEDIOL , INULIN , CAPSICUM ANNUUM FRUIT EXTRACT , SODIUM CITRATE , HYDROXYPROPYL METHYLCELLULOSE , OCTYLDODECETH,16 , CITRIC ACID , BUTYLENE GLYCOL', 'Evitare il contatto con gli occhi.\r\nTestato sotto controllo dermatologico.\r\nFormula senza silicone.'),
(58, 'Smart Clinical Repair™ ', 'Crema antirughe', 'Crema antirughe dalla texture leggera per tutti i tipi di pelle: aiuta a rafforzare e nutrire la pelle rendendola più levigata e giovane.\r\n\r\nRafforza e idrata, ripara visibilmente linee e rughe.', 'viso/9.png', 'CLINIQUE', 'Antietà', 'Applica due volte al giorno, mattina e sera.\r\n\r\nApplica su viso e collo dopo il siero Clinique Smart Clinical Repair Wrinkle Correcting Serum', 'WATER\\AQUA\\EAU_GLYCERIN_ISOSTEARYL NEOPENTANOATE_BUTYLENE GLYCOL_GLYCERYL STEARATE_PEG-100 STEARATE_DIMETHICONE_CETEARYL ALCOHOL_ ACETYL HEXAPEPTIDE-8_ACETYL OCTAPEPTIDE-3_AMINOPROPYL ASCORBYL PHOSPHATE_ PALMITOYL TETRAPEPTIDE-7_ALGAE EXTRACT_SODIUM HYALURONATE_PALMITOYL', 'Nessuna avvertenza.'),
(59, 'The Spot Stop', 'Anti imperfezioni con AHA+PHA', 'Trattamento mirato per le imperfezioni con olio di tea tree, acido glicolico e gluconolattone, che lenisce l’infiammazione, combatte i batteri e minimizza i pori, per una pelle più pulita e sana.\r\n\r\nThe Spot Stop è il tuo alleato nella lotta contro i le imperfezioni. L’olio di tea tree offre una protezione antibatterica naturale, l’acido glicolico esfolia delicatamente per prevenire i pori ostruiti e il gluconolattone lenisce e calma le irritazioni. Questa formula ad azione rapida aiuta a perfezionare la texture della pelle, lasciandola equilibrata e luminosa.', 'viso/10.png', 'YEPODA', 'Antietà', '1. Detergi il viso in profondità e prepara la pelle come di consueto.\n2. Preleva una quantità di prodotto pari a una lenticchia e applicala direttamente sui punti critici.\n3. Massaggia leggermente fino a completo assorbimento e lascia agire la formula.', 'AQUA (WATER), GLYCERIN, NIACINAMIDE (VITAMIN B3), BUTYLENE GLYCOL, BUTYROSPERMUM PARKII (SHEA) BUTTER, CAPRYLIC/CAPRIC TRIGLYCERIDE, DICAPRYLYL CARBONATE, CETEARYL OLIVATE, POLYGLYCERYL-3 DISTEARATE, 1,2-HEXANEDIOL, SORBITAN OLIVATE, GLYCOLIC ACID, C14-22 ALCOHOLS, OLEA EUROPAEA (OLIVE) FRUIT OIL', 'Nessuna avvertenza.'),
(60, 'Glycolic Acid 7% Toning', 'Lozione Viso Esfoliante', 'L’Acido Glicolico è un Alfa-Idrossiacido (AHA) dalle proprietà esfolianti. Questa soluzione tonificante concentrata al 7% assicura un’esfoliazione leggera per migliorare l’uniformità e la luminosità dell’incarnato.\r\nInoltre, sul lungo termine, la formula migliora la grana cutanea.\r\n\r\nContiene un derivato del pepe della Tasmania, in grado di ridurre l’irritazione spesso associata all’uso degli acidi della frutta.', 'viso/11.png', 'THE ORDINARY', 'Esfolianti', 'Usare solo una volta al giorno, preferibilmente la sera. Versare la soluzione su un dischetto/batuffolo di cotone e passarlo su viso e collo detersi.', 'Aqua (Water). Glycolic Acid. Rosa damascena flower water. Centaurea cyanus flower water. Aloe Barbadensis Leaf Water. Propanediol. Glycerin. Triethanolamine. Aminomethyl Propanol. Panax Ginseng Root Extract', 'Questo prodotto contiene un alfa-idrossiacido (AHA), che potrebbe aumentare la sensibilità della pelle al sole e il rischio di scottature.'),
(61, 'Glaze Craze', 'Siero Labbra Colorato', 'Scopri Glaze Craze Tinted Lip Serum, il tuo nuovo balsamo labbra colorato e idratante!\r\nImmagina labbra morbide, idratate e leggermente colorate, con una brillantezza radiosa. Il Glaze Craze Tinted Lip Serum è molto più di un semplice balsamo per le labbra: è il nuovo must-have per labbra naturalmente sublimi.\r\n\r\nCos’è?\r\nGrazie alla texture leggera e brillante, scivola alla perfezione sulle labbra, per un finish luminoso e piacevole per tutta la giornata. Perfetto per un look naturale o per un tocco di colore più intenso, questo balsamo si adatta a tutte le esigenze!\r\n\r\nCosa c’è nella formula?\r\n•Potenti idratanti: forniscono un’idratazione prolungata, per labbra morbide e lisce, senza sensazione di secchezza.\r\n•Colore stratificabile: pigmenti delicati che esaltano il colore naturale delle labbra, per un effetto immediato bonne mine.\r\n•Effetto glowy: il finish luminoso offre una brillantezza naturale, senza effetto appiccicoso.\r\n\r\nIl risultato?\r\nLabbra idratate, nutrite e brillanti, con un tocco di colore naturale che dura tutto il giorno. È il perfetto accessorio beauty per labbra sempre pronte a brillare.', 'viso/12.png', 'LANEIGE', 'Idratanti', 'Applicare un sottile strato di Lip Glaze Craze direttamente sulle labbra per aggiungere brillantezza.', 'DIISOSTEARYL MALATE, BIS-BEHENYL/ISOSTEARYL/PHYTOSTERYL DIMER DILINOLEYL DIMER DILINOLEATE, BIS-DIGLYCERYL POLYACYLADIPATE-2, HYDROGENATED POLYISOBUTENE, OCTYLDODECANOL, MICROCRYSTALLINE WAX', 'Solo per uso esterno. Evitare il contatto diretto con gli occhi. In caso di contatto con gli occhi, risciacquare con abbondante acqua.');



INSERT INTO `disponibilità` (`IDdisponibilità`, `taglia`, `prezzo`, `quantità`, `IDprodotto`, `usernameVenditore`) VALUES
(101, '100ml', 22, 8, 1, 'pureessence'),
(102, '400ml', 18, 10, 2, 'pureessence'),
(103, '90ml', 15, 50, 3, 'pureessence'),
(104, '50ml', 28, 20, 4, 'pureessence'),
(105, '30ml', 29, 30, 5, 'pureessence'),
(106, '35ml', 66, 10, 6, 'pureessence'),
(107, '150ml', 12, 10, 2, 'pureessence'),
(1061, '50ml', 100, 10, 6, 'pureessence'),
(1062, '100ml', 136, 10, 6, 'pureessence'),
(1063, '200ml', 289, 10, 6, 'pureessence'),
(1081, '30ml', 52, 5, 8, 'pureessence'),
(1082, '50ml', 74.9, 5, 8, 'pureessence'),
(1083, '100ml', 101.5, 6, 8, 'pureessence'),
(1084, '150ml', 123.9, 9, 8, 'pureessence'),
(1091, '35ml', 62.93, 5, 9, 'pureessence'),
(1092, '50ml', 86.8, 10, 9, 'pureessence'),
(1093, '80ml', 104.9, 15, 9, 'pureessence'),
(1094, '150ml', 179, 7, 9, 'pureessence'),
(1101, '30ml', 85.9, 4, 10, 'pureessence'),
(1102, '50ml', 121, 7, 10, 'pureessence'),
(1103, '90ml', 164, 13, 10, 'pureessence'),
(1111, '30ml', 67.42, 10, 11, 'pureessence'),
(1112, '50ml', 96, 6, 11, 'pureessence'),
(1113, '90ml', 171, 8, 11, 'pureessence'),
(1121, '50ml', 99, 7, 12, 'pureessence'),
(1122, '100ml', 134, 8, 12, 'pureessence'),
(1131, '50ml', 115, 10, 13, 'pureessence'),
(1132, '100ml', 153, 10, 13, 'pureessence'),
(1151, '30ml', 71, 7, 15, 'pureessence'),
(1152, '50ml', 84, 5, 15, 'pureessence'),
(1153, '100ml', 116, 10, 15, 'pureessence'),
(1162, '100ml', 150, 10, 16, 'pureessence'),
(1171, '50ml', 94.9, 6, 17, 'pureessence'),
(1172, '100ml', 127, 5, 17, 'pureessence'),
(1173, '200ml', 149, 9, 17, 'pureessence'),
(1181, '30ml', 160, 5, 18, 'pureessence'),
(1182, '50ml', 264, 10, 18, 'pureessence'),
(1191, '5.2g', 41, 6, 19, 'pureessence'),
(1201, '9ml', 35.2, 7, 20, 'pureessence'),
(1211, '7.5ml', 29, 8, 21, 'pureessence'),
(1221, '50ml', 11.9, 5, 22, 'pureessence'),
(1231, '80g', 25, 4, 23, 'pureessence'),
(1241, '6g', 39, 8, 24, 'pureessence'),
(1251, '4g', 23, 9, 25, 'pureessence'),
(1261, '8ml', 29.9, 10, 26, 'pureessence'),
(1271, '1g', 18, 9, 27, 'pureessence'),
(1281, '30ml', 48, 10, 28, 'pureessence'),
(1291, '16g', 72, 8, 29, 'pureessence'),
(1301, '8ml', 28, 10, 30, 'pureessence'),
(1311, '75ml', 22, 5, 31, 'pureessence'),
(1312, '150ml', 36.9, 6, 31, 'pureessence'),
(1321, '90ml', 26, 5, 32, 'pureessence'),
(1331, '90ml', 26, 5, 33, 'pureessence'),
(1341, '100ml', 21, 5, 34, 'pureessence'),
(1351, '240ml', 19.5, 6, 35, 'pureessence'),
(1361, '75ml', 56, 5, 36, 'pureessence'),
(1371, '53ml', 22.5, 5, 37, 'pureessence'),
(1381, '75ml', 22, 5, 38, 'pureessence'),
(1382, '150ml', 36.9, 4, 38, 'pureessence'),
(1391, '125ml', 51, 6, 39, 'pureessence'),
(1401, '100ml', 20, 5, 40, 'pureessence'),
(1411, '250ml', 42, 5, 41, 'pureessence'),
(1421, '40ml', 14, 4, 42, 'pureessence'),
(1431, '225ml', 35.5, 8, 43, 'pureessence'),
(1441, '50ml', 21.9, 6, 44, 'pureessence'),
(1442, '200ml', 32.5, 5, 44, 'pureessence'),
(1451, '75ml', 21, 5, 45, 'pureessence'),
(1452, '230ml', 42, 6, 45, 'pureessence'),
(1461, '50ml', 39.9, 6, 46, 'pureessence'),
(1462, '20ml', 22, 7, 46, 'pureessence'),
(1471, '190ml', 39.5, 10, 47, 'pureessence'),
(1481, '47ml', 26, 6, 48, 'pureessence'),
(1491, '250ml', 44.5, 7, 49, 'pureessence'),
(1501, '70ml', 33, 5, 50, 'pureessence'),
(1511, '50ml', 16.9, 5, 51, 'pureessence'),
(1512, '150ml', 33, 8, 51, 'pureessence'),
(1521, '50ml', 18, 5, 52, 'pureessence'),
(1531, '50ml', 112.5, 5, 53, 'pureessence'),
(1541, '50ml', 40.5, 4, 54, 'pureessence'),
(1551, '50ml', 118, 7, 55, 'pureessence'),
(1561, '50ml', 110, 6, 56, 'pureessence'),
(1571, '30ml', 56, 9, 57, 'pureessence'),
(1581, '50ml', 71.25, 9, 58, 'pureessence'),
(1591, '20ml', 19, 8, 59, 'pureessence'),
(1601, '30ml', 11.5, 8, 60, 'pureessence'),
(1602, '60ml', 19.9, 9, 60, 'pureessence'),
(1611, '12g', 22, 8, 61, 'pureessence'),
(11141, '30ml', 70, 8, 14, 'pureessence'),
(11142, '50ml', 85.9, 10, 14, 'pureessence'),
(11143, '100ml', 122, 8, 14, 'pureessence'),
(11144, '200ml', 175, 6, 14, 'pureessence'),
(11161, '50ml', 109, 5, 16, 'pureessence');
